MAX_LENGTH_TITLE = 256
MAX_LENGTH_SLUG = 64

# Константы для Location
LOCATION_NAME_MAX_LENGTH = 256

# Константы для Category
CATEGORY_TITLE_MAX_LENGTH = 256
CATEGORY_DESCRIPTION_MAX_LENGTH = None
CATEGORY_SLUG_MAX_LENGTH = 64

# Константы для Post
POST_TITLE_MAX_LENGTH_TITLE = 256
POST_TEXT_MAX_LENGTH_TITLE = None
POST_PER_PAGE_MAIN = 5
